import type { ConnectListingCard } from "./types";

/** Static listings for local UI when connect_listings table is not migrated yet. */
export const CONNECT_DEMO_FIXTURES: ConnectListingCard[] = [
  {
    id: 9001,
    owner_id: "00000000-0000-0000-0000-000000000001",
    platform: "snapchat",
    handle: "demo_luna_snap",
    display_name: "Luna",
    age: 24,
    gender: "female",
    orientation: "bi",
    country: "US",
    bio: "Demo listing — run npm run db:push then npm run seed:demo for live DB rows.",
    bulletin: "Online now · reply fast 💋",
    bulletin_updated_at: null,
    avatar_media_id: null,
    is_vip: true,
    vip_until: null,
    fire_pin_until: new Date(Date.now() + 86400000).toISOString(),
    stealth_pin_until: null,
    last_active_at: new Date(Date.now() - 3600000).toISOString(),
    views_count: 12400,
    click_count: 890,
    score: 92,
    created_at: new Date().toISOString(),
    avatar_url: "https://picsum.photos/seed/aof-connect-1/480/640",
    tags: ["verified", "fast reply"],
  },
  {
    id: 9002,
    owner_id: "00000000-0000-0000-0000-000000000001",
    platform: "telegram",
    handle: "demo_aria_tg",
    display_name: "Aria",
    age: 22,
    gender: "female",
    orientation: "straight",
    country: "GB",
    bio: null,
    bulletin: "Free preview in bio",
    bulletin_updated_at: null,
    avatar_media_id: null,
    is_vip: true,
    vip_until: null,
    fire_pin_until: null,
    stealth_pin_until: null,
    last_active_at: new Date(Date.now() - 7200000).toISOString(),
    views_count: 8900,
    click_count: 420,
    score: 78,
    created_at: new Date().toISOString(),
    avatar_url: "https://picsum.photos/seed/aof-connect-2/480/640",
    tags: ["custom", "gfe"],
  },
  {
    id: 9003,
    owner_id: "00000000-0000-0000-0000-000000000001",
    platform: "snapchat",
    handle: "demo_jade_snap",
    display_name: "Jade",
    age: 26,
    gender: "female",
    orientation: "lesbian",
    country: "CA",
    bio: null,
    bulletin: "Weekend specials",
    bulletin_updated_at: null,
    avatar_media_id: null,
    is_vip: false,
    vip_until: null,
    fire_pin_until: new Date(Date.now() + 86400000).toISOString(),
    stealth_pin_until: null,
    last_active_at: new Date(Date.now() - 18000000).toISOString(),
    views_count: 5600,
    click_count: 210,
    score: 65,
    created_at: new Date().toISOString(),
    avatar_url: "https://picsum.photos/seed/aof-connect-3/480/640",
    tags: ["cosplay"],
  },
  {
    id: 9004,
    owner_id: "00000000-0000-0000-0000-000000000001",
    platform: "telegram",
    handle: "demo_mia_tg",
    display_name: "Mia",
    age: 23,
    gender: "female",
    orientation: "bi",
    country: "DE",
    bio: null,
    bulletin: "Custom requests open",
    bulletin_updated_at: null,
    avatar_media_id: null,
    is_vip: false,
    vip_until: null,
    fire_pin_until: null,
    stealth_pin_until: null,
    last_active_at: new Date(Date.now() - 86400000).toISOString(),
    views_count: 3200,
    click_count: 150,
    score: 48,
    created_at: new Date().toISOString(),
    avatar_url: "https://picsum.photos/seed/aof-connect-4/480/640",
    tags: ["fitness"],
  },
  {
    id: 9005,
    owner_id: "00000000-0000-0000-0000-000000000001",
    platform: "instagram",
    handle: "demo_nova_ig",
    display_name: "Nova",
    age: 25,
    gender: "female",
    orientation: "straight",
    country: "US",
    bio: null,
    bulletin: "Link in story highlights",
    bulletin_updated_at: null,
    avatar_media_id: null,
    is_vip: true,
    vip_until: null,
    fire_pin_until: null,
    stealth_pin_until: null,
    last_active_at: new Date(Date.now() - 43200000).toISOString(),
    views_count: 7100,
    click_count: 380,
    score: 71,
    created_at: new Date().toISOString(),
    avatar_url: "https://picsum.photos/seed/aof-connect-5/480/640",
    tags: ["verified"],
  },
  {
    id: 9006,
    owner_id: "00000000-0000-0000-0000-000000000001",
    platform: "telegram",
    handle: "demo_skye_tg",
    display_name: "Skye",
    age: 28,
    gender: "couple",
    orientation: "straight",
    country: "US",
    bio: null,
    bulletin: "Couple account · both reply",
    bulletin_updated_at: null,
    avatar_media_id: null,
    is_vip: true,
    vip_until: null,
    fire_pin_until: null,
    stealth_pin_until: null,
    last_active_at: new Date(Date.now() - 10800000).toISOString(),
    views_count: 9800,
    click_count: 520,
    score: 82,
    created_at: new Date().toISOString(),
    avatar_url: "https://picsum.photos/seed/aof-connect-6/480/640",
    tags: ["gfe"],
  },
];

export function filterDemoFixtures(filters: {
  platform?: string;
  gender?: string;
  vip?: boolean;
  hasPhoto?: boolean;
}): ConnectListingCard[] {
  return CONNECT_DEMO_FIXTURES.filter((l) => {
    if (filters.platform && l.platform !== filters.platform) return false;
    if (filters.gender && l.gender !== filters.gender) return false;
    if (filters.vip && !l.is_vip) return false;
    if (filters.hasPhoto && !l.avatar_url) return false;
    return true;
  });
}
